# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9006534fff5c40bbfdae96f9f42a7b50d50a9c608ffa6817428223dded75de392ca46cb9c9ff996a661b39fd23ba063e18d1f22a7c70d9ef23cf62f6ed8cd47

test:
  secret_key_base: df505c0396a0e2b13b68cacf5a823fff84e243ec3f6b95d9c46bb24a04ab4bc2af0ca014ba1b334f0601443c25c17344a2e5ec4b15997d49dc1ab1e788b7c507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
